object Accompanist {
    private const val group = "com.google.accompanist"
    fun insets(ver: String = DYNAMIC_VERSION) = "$group:accompanist-insets:$ver"
    fun insets_ui(ver: String = DYNAMIC_VERSION) = "$group:accompanist-insets-ui:$ver"
    fun systemuicontroller(ver: String = DYNAMIC_VERSION) = "$group:accompanist-systemuicontroller:$ver"
    fun appcompat_theme(ver: String = DYNAMIC_VERSION) = "$group:accompanist-appcompat-theme:$ver"
    fun pager(ver: String = DYNAMIC_VERSION) = "$group:accompanist-pager:$ver"
    fun pager_indicators(ver: String = DYNAMIC_VERSION) = "$group:accompanist-pager-indicators:$ver"
    fun swiperefresh(ver: String = DYNAMIC_VERSION) = "$group:accompanist-swiperefresh:$ver"
    fun placeholder(ver: String = DYNAMIC_VERSION) = "$group:accompanist-placeholder:$ver"
    fun placeholder_material(ver: String = DYNAMIC_VERSION) = "$group:accompanist-placeholder-material:$ver"
    fun drawablepainter(ver: String = DYNAMIC_VERSION) = "$group:accompanist-drawablepainter:$ver"
    fun flowlayout(ver: String = DYNAMIC_VERSION) = "$group:accompanist-flowlayout:$ver"
    fun permissions(ver: String = DYNAMIC_VERSION) = "$group:accompanist-permissions:$ver"
    fun navigation_animation(ver: String = DYNAMIC_VERSION) = "$group:accompanist-navigation-animation:$ver"
    fun navigation_material(ver: String = DYNAMIC_VERSION) = "$group:accompanist-navigation-material:$ver"
}